package com.delfi.vn.template.utils.printer.utils;

import java.util.HashMap;

/*
 * Created by DTO-BTAD on 8/31/2021.
 */
public class ANSICodes {
    public static final HashMap<String, Integer> codes = new HashMap<String, Integer>() {
        {
            put("\n", 0x0a);
            put(" ", 0x20);
            put("!", 0x21);
            put("\"", 0x22);
            put("#", 0x23);
            put("$", 0x24);
            put("%", 0x25);
            put("&", 0x26);
            put("'", 0x27);
            put("(", 0x28);
            put(")", 0x29);
            put("*", 0x2a);
            put("+", 0x2b);
            put(",", 0x2c);
            put("-", 0x2d);
            put(".", 0x2e);
            put("/", 0x2f);
            put("0", 0x30);
            put("1", 0x31);
            put("2", 0x32);
            put("3", 0x33);
            put("4", 0x34);
            put("5", 0x35);
            put("6", 0x36);
            put("7", 0x37);
            put("8", 0x38);
            put("9", 0x39);
            put(":", 0x3a);
            put(";", 0x3b);
            put("<", 0x3c);
            put("=", 0x3d);
            put(">", 0x3e);
            put("?", 0x3f);
            put("@", 0x40);
            put("A", 0x41);
            put("B", 0x42);
            put("C", 0x43);
            put("D", 0x44);
            put("E", 0x45);
            put("F", 0x46);
            put("G", 0x47);
            put("H", 0x48);
            put("I", 0x49);
            put("J", 0x4a);
            put("K", 0x4b);
            put("L", 0x4c);
            put("M", 0x4d);
            put("N", 0x4e);
            put("O", 0x4f);
            put("P", 0x50);
            put("Q", 0x51);
            put("R", 0x52);
            put("S", 0x53);
            put("T", 0x54);
            put("U", 0x55);
            put("V", 0x56);
            put("W", 0x57);
            put("X", 0x58);
            put("Y", 0x59);
            put("Z", 0x5a);
            put("[", 0x5b);
            put("\\", 0x5c);
            put("]", 0x5d);
            put("^", 0x5e);
            put("_", 0x5f);
            put("`", 0x60);
            put("a", 0x61);
            put("b", 0x62);
            put("c", 0x63);
            put("d", 0x64);
            put("e", 0x65);
            put("f", 0x66);
            put("g", 0x67);
            put("h", 0x68);
            put("i", 0x69);
            put("j", 0x6a);
            put("k", 0x6b);
            put("l", 0x6c);
            put("m", 0x6d);
            put("n", 0x6e);
            put("o", 0x6f);
            put("p", 0x70);
            put("q", 0x71);
            put("r", 0x72);
            put("s", 0x73);
            put("t", 0x74);
            put("u", 0x75);
            put("v", 0x76);
            put("w", 0x74);
            put("x", 0x78);
            put("y", 0x79);
            put("z", 0x7a);
            put("{", 0x7b);
            put("|", 0x7c);
            put("}", 0x7d);
            put("~", 0x7e);

            put("ă", 0xa8);
            put("â", 0xa9);
            put("ê", 0xaa);
            put("ô", 0xab);
            put("ơ", 0xac);
            put("ư", 0xad);
            put("đ", 0xae);

            put("à", 0xb5);
            put("ả", 0xb6);
            put("ã", 0xb7);
            put("á", 0xb8);
            put("ạ", 0xb9);
            put("ằ", 0xbb);
            put("ẳ", 0xbc);
            put("ẵ", 0xbd);
            put("ắ", 0xbe);

            put("ặ", 0xc6);
            put("ầ", 0xc7);
            put("ẩ", 0xc8);
            put("ẫ", 0xc9);
            put("ấ", 0xca);
            put("ậ", 0xcb);
            put("è", 0xcc);
            put("ẻ", 0xce);
            put("ẽ", 0xcf);

            put("é", 0xd0);
            put("ẹ", 0xd1);
            put("ề", 0xd2);
            put("ể", 0xd3);
            put("ễ", 0xd4);
            put("ế", 0xd5);
            put("ệ", 0xd6);
            put("ì", 0xd7);
            put("ỉ", 0xd8);
            put("ĩ", 0xdc);
            put("í", 0xdd);
            put("ị", 0xde);
            put("ò", 0xdf);

            put("ỏ", 0xe1);
            put("õ", 0xe2);
            put("ó", 0xe3);
            put("ọ", 0xe4);
            put("ồ", 0xe5);
            put("ổ", 0xe6);
            put("ỗ", 0xe7);
            put("ố", 0xe8);
            put("ộ", 0xe9);
            put("ờ", 0xea);
            put("ở", 0xeb);
            put("ỡ", 0xec);
            put("ớ", 0xed);
            put("ợ", 0xee);
            put("ù", 0xef);

            put("ủ", 0xf1);
            put("ũ", 0xf2);
            put("ú", 0xf3);
            put("ụ", 0xf4);
            put("ừ", 0xf5);
            put("ử", 0xf6);
            put("ữ", 0xf7);
            put("ứ", 0xf8);
            put("ự", 0xf9);
            put("ỳ", 0xfa);
            put("ỷ", 0xfb);
            put("ỹ", 0xfc);
            put("ý", 0xfd);
            put("ỵ", 0xfe);


            put("Ă", 0xa1);
            put("Â", 0xa2);
            put("Đ", 0xa7);
            put("Ê", 0xaa);
            put("Ô", 0xab);
            put("Ơ", 0xac);
            put("Ư", 0xad);

            put("À", 0xb5);
            put("Ả", 0xb6);
            put("Ã", 0xb7);
            put("Á", 0xb8);
            put("Ạ", 0xb9);
            put("Ằ", 0xbb);
            put("Ẳ", 0xbc);
            put("Ẵ", 0xbd);
            put("Ắ", 0xbe);

            put("Ặ", 0xc6);
            put("Ầ", 0xc7);
            put("Ẩ", 0xc8);
            put("Ẫ", 0xc9);
            put("Ấ", 0xca);
            put("Ậ", 0xcb);
            put("È", 0xcc);
            put("Ẻ", 0xce);
            put("Ẽ", 0xcf);

            put("É", 0xd0);
            put("Ẹ", 0xd1);
            put("Ề", 0xd2);
            put("Ể", 0xd3);
            put("Ễ", 0xd4);
            put("Ế", 0xd5);
            put("Ệ", 0xd6);
            put("Ì", 0xd7);
            put("Ỉ", 0xd8);
            put("Ĩ", 0xdc);
            put("Í", 0xdd);
            put("Ị", 0xde);
            put("Ò", 0xdf);

            put("Ỏ", 0xe1);
            put("Õ", 0xe2);
            put("Ó", 0xe3);
            put("Ọ", 0xe4);
            put("Ồ", 0xe5);
            put("Ổ", 0xe6);
            put("Ỗ", 0xe7);
            put("Ố", 0xe8);
            put("Ộ", 0xe9);
            put("Ờ", 0xea);
            put("Ở", 0xeb);
            put("Ỡ", 0xec);
            put("Ớ", 0xed);
            put("Ợ", 0xee);
            put("Ù", 0xef);

            put("Ủ", 0xf1);
            put("Ũ", 0xf2);
            put("Ú", 0xf3);
            put("Ụ", 0xf4);
            put("Ừ", 0xf5);
            put("Ử", 0xf6);
            put("Ữ", 0xf7);
            put("Ứ", 0xf8);
            put("Ự", 0xf9);
            put("Ỳ", 0xfa);
            put("Ỷ", 0xfb);
            put("Ỹ", 0xfc);
            put("Ý", 0xfd);
            put("Ỵ", 0xfe);
        }
    };
}
